# Generated by Django 3.1.11 on 2021-05-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_auto_20210518_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='discription',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
