version: "3.9"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - .dbdata:/var/lib/mysqld
        environment:
            MYSQL_DATABASE: 'django_oauth'
            MYSQL_ROOT_PASSWORD: Mitcutenhat123
        ports:
            - "8066:3306"
    django:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      container_name: django
      depends_on:
        - db
      volumes:
        - .:/app:z
      ports:
        - "8000:8000"
