# Generated by Django 3.1.11 on 2021-05-21 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeproduct',
            name='flag',
        ),
    ]
