# Generated by Django 3.1.11 on 2021-05-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_typeproduct_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='description',
            field=models.TextField(),
        ),
    ]
